apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: i62e0nyl6-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:55978eae2b34a12a0030f5f952c8ec44778e46c3@sha256:ff5c559a6ab3056610b64d40c410fb2c0920dc548a69c77f99ce869d62dafa01
          name: container-image
